# Generated by Django 2.2.2 on 2019-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
