# Generated by Django 2.2.2 on 2019-06-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190610_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='topic',
            new_name='topic_name',
        ),
    ]
