# Generated by Django 2.2.2 on 2019-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20190620_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='auth',
            field=models.ForeignKey(on_delete=True, to='pet.Auth'),
        ),
    ]
