# Generated by Django 2.2.2 on 2019-06-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190613_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aiticle',
            new_name='article',
        ),
    ]
